return {}
-- return {
--     "sphamba/smear-cursor.nvim",
--     opts = {
--         cursor_color = "#ff8800",
--         stiffness = 0.8,               -- 0.6      [0, 1]
--         trailing_stiffness = 0.5,      -- 0.3      [0, 1]
--         distance_stop_animating = 0.1, -- 0.1      > 0
--         hide_target_hack = true,       -- true     boolean
--         smear_to_cmd = false
--     },
-- }
