return {
    ' danna ~~',
    ' daua ~~~',
    ' dinna ~~',
    ' hinna ~~',
    ' dauna ~~',
    ' doldi ~~',

    ' hans ~~~',
    ' franz ~~',
    ' fritz ~~',
    ' günter ~',
    ' günther ',
    ' robert ~',
    ' roland ~',

    '~ 0 ~~~~~',
    '~ 1 ~~~~~',
    '~ 2 ~~~~~',
    '~ 3 ~~~~~',
    '~ 4 ~~~~~',
    '~ 6 ~~~~~',
    '~ 7 ~~~~~',
    '~ 8 ~~~~~',
    '~ 9 ~~~~~',
}
