local c = require('theme/colors')

return {
    phpAssignByRef = { fg = c.text },
    phpBackslashSequences = { fg = c.orange8 },
    phpBoolean = { fg = c.orange8 },
    phpClasses = { fg = c.rose5 },
    phpCommentTitle = { fg = c.grey1 },
    phpComparison = { fg = c.text },
    phpConditional = { fg = c.blue4 },
    phpConstant = { fg = c.blue7 },
    phpCoreConstant = { fg = c.blue7 },
    phpDefine = { fg = c.blue7 },
    phpDocParam = { fg = c.blue6 },
    phpDocTags = { fg = c.grey1 },
    phpException = { fg = c.blue4 },
    phpFunctions = { fg = c.purple4 },
    phpIdentifier = { fg = c.text },
    phpInclude = { fg = c.blue8 },
    phpKeyword = { fg = c.blue4 },
    phpLabel = { fg = c.blue4 },
    phpMemberSelector = { fg = c.text },
    phpMethods = { fg = c.text },
    phpNumber = { fg = c.orange8 },
    phpOperator = { fg = c.text },
    phpParent = { fg = c.text },
    phpRegion = { fg = c.grey0 },
    phpRelation = { fg = c.text },
    phpRepeat = { fg = c.blue4 },
    phpSpecialFunction = { fg = c.yellow4 },
    phpStatement = { fg = c.blue4 },
    phpStorageClass = { fg = c.blue8 },
    phpStringBacktick = { fg = c.orange4 },
    phpStringDouble = { fg = c.orange4 },
    phpStringSingle = { fg = c.orange4 },
    phpStructure = { fg = c.blue7 },
    phpType = { fg = c.orange7 },
    phpVarSelector = { fg = c.text },

    htmlComment = { fg = c.grey2 },
    htmlCommentPart = { fg = c.grey2 },
    htmlTagName = { fg = c.orange7 },
    htmlEndTag = { fg = c.orange7 },
    htmlTag = { fg = c.orange7 },
    htmlTagN = { fg = c.orange7 },
    htmlArg = { fg = c.yellow5 },
    htmlString = { fg = c.orange4 },
    htmlSpecialTagName = { fg = c.orange9 },
    htmlLink = { fg = c.white },
    htmlTitle = { fg = c.white },
    htmlH1 = { fg = c.white },
    htmlH2 = { fg = c.white },
    htmlH3 = { fg = c.white },
    htmlH4 = { fg = c.white },
    htmlH5 = { fg = c.white },
    htmlH6 = { fg = c.white },
    htmlSpecialChar = { fg = c.salmon5 },

    htmlHtmxAttr = { fg = c.green3 },
    htmlHtmxAttrParam = { fg = c.green0 },

    pythonBuiltin = { fg = c.purple4 },
    pythonConst = { fg = c.green4 },
    pythonAsync = { fg = c.blue4 },
    pythonClass = { fg = c.orange3 },
    pythonComment = { fg = c.grey2 },
    pythonConditional = { fg = c.blue4 },
    pythonDecorator = { fg = c.orange6 },
    pythonDecoratorName = { fg = c.brown1 },
    pythonDocString = { fg = c.grey2 },
    pythonEscape = { fg = c.orange6 },
    pythonException = { fg = c.blue4 },
    pythonExceptions = { fg = c.yellow5 },
    pythonFunction = { fg = c.text },
    pythonInclude = { fg = c.blue4 },
    pythonNumber = { fg = c.orange9 },
    pythonOperator = { fg = c.blue4 },
    pythonRawString = { fg = c.orange4 },
    pythonQuotes = { fg = c.orange4 },
    pythonRepeat = { fg = c.blue4 },
    pythonSelf = { fg = c.green2 },
    pythonStatement = { fg = c.blue7 },
    pythonString = { fg = c.orange4 },
    pythonUnderUnder = { fg = c.orange6 },

    makoEnd = { fg = c.blue4 },

    sqlConstant = { fg = c.blue2 },
    sqlNumber = { fg = c.rose2 },
    sqlType = { fg = c.salmon5 },
    sqlTypeConversion = { fg = c.salmon5 },
    sqlCreateTextSearchKeyword = { fg = c.salmon5 },
    sqlString = { fg = c.orange1 },
    sqlFlow = { fg = c.yellow5 },
    sqlStatement = { fg = c.orange4 },
    sqlKeyword = { fg = c.orange4 },
    sqlOperator = { fg = c.orange4 },
    sqlPlpgsqlKeyword = { fg = c.orange4 },
    sqlFunction = { fg = c.green2 },
    sqlCustomFunction = { fg = c.green2 },
    sqlJsonFunction = { fg = c.green2 },
    sqlPostgresFunction = { fg = c.green2 },
    sqlIdentifier = { fg = c.white },
    sqlPublicSchema = { fg = c.rose6 },
    sqlBoolean = { fg = c.rose2 },
    sqlSpecial = { fg = c.rose2 },
    sqlUnreserved = { fg = c.text },
    sqlMakoDelim = { fg = c.rose6 },
    sqlMakoEnd = { fg = c.rose6 },
    sqlPhpDelim = { fg = c.rose6 },
    sqlPhpRegion = { fg = c.rose2 },
    sqlColonParam = { fg = c.blue6 },
    sqlPostgresDelim = { fg = c.blue6 },
    sqlPostgresVariable = { fg = c.blue6 },

    sqlQumaPlaceholder = { fg = c.rose2 },
    sqlQumaPlaceholderText = { fg = c.rose2 },
    sqlQumaPlaceholderDelim = { fg = c.rose6 },

    caddyHost = { fg = c.blue6 },
    caddyDirective = { fg = c.orange6 },
    -- caddySubdirective = { fg = c.rose9 },
    -- caddyImport = { fg = c.sea5 },
    -- caddySnippetDef = { fg = c.purple3 },
    -- caddySnippet = { fg = c.blue6 },
    -- caddyPlaceholder = { fg = c.yellow5 },
    -- caddyString = { fg = c.orange3 },
    -- caddyComment = { fg = c.grey2 },
    -- caddyNamedMatcher = { fg = c.green2 },
    -- caddyNamedMatcherDef = { fg = c.green2 },
    caddyFrankenPhpDirective = { fg = c.blue7 },
    caddyFrankenPhpSubdirective = { fg = c.orange7 },
}
