local p = require('serious/palette')

local M = {}

M.gui = {
    ColorColumn              = { link = 'CursorLine' },
    Conceal                  = { fg = p.none, bg = p.none },
    CurSearch                = { fg = p.black, bg = p.blue1 },
    Cursor                   = { fg = p.black, bg = p.blue1 },
    CursorColumn             = { fg = p.none, bg = p.grey4 },
    CursorIM                 = { fg = p.black, bg = p.blue1 },
    CursorLine               = { fg = p.none, bg = p.none },
    CursorLineFold           = { fg = p.none, bg = p.text },
    CursorLineNr             = { fg = p.yellow4, bg = p.none },
    CursorLineSign           = { fg = p.grey4, bg = p.none },
    Directory                = { fg = p.text, bg = p.none },
    EndOfBuffer              = { fg = p.grey4, bg = p.none },
    ErrorMsg                 = { fg = p.red2, bg = p.none },
    FloatBorder              = { fg = p.blue1, bg = p.none },
    FloatFooter              = { link = 'FloatBorder' },
    FloatTitle               = { fg = p.text, bg = p.black },
    FoldColumn               = { fg = p.none, bg = p.none },
    Folded                   = { fg = p.none, bg = p.grey4 },
    IncSearch                = { link = 'CurSearch' },
    LineNr                   = { fg = p.grey4, bg = p.none },
    LineNrAbove              = { fg = p.grey4, bg = p.none },
    LineNrBelow              = { fg = p.grey4, bg = p.none },
    MatchParen               = { fg = p.none, bg = p.grey4 },
    ModeMsg                  = { fg = p.text, bg = p.black },
    MoreMsg                  = { fg = p.text, bg = p.black },
    MsgArea                  = { fg = p.none, bg = p.black },
    MsgSeparator             = { fg = p.grey4, bg = p.black },
    NonText                  = { fg = p.grey4, bg = p.none },
    Normal                   = { fg = p.text, bg = p.black },
    NormalFloat              = { link = 'Normal' },
    NormalNC                 = { link = 'Normal' },
    Pmenu                    = { fg = p.text, bg = p.black },
    PmenuExtra               = { fg = p.blue5, bg = p.black },
    PmenuExtraSel            = { fg = p.grey4, bg = p.blue4 },
    PmenuKind                = { fg = p.blue1, bg = p.black },
    PmenuKindSel             = { fg = p.sea4, bg = p.blue4 },
    PmenuSbar                = { fg = p.sea4, bg = p.black },
    PmenuSel                 = { fg = p.none, bg = p.blue4 },
    PmenuThumb               = { fg = p.grey4, bg = p.grey3 },
    Question                 = { fg = p.blue1, bg = p.black },
    QuickFixLine             = { fg = p.text, bg = p.none },
    Search                   = { link = 'CurSearch' },
    SignColumn               = { fg = p.none, bg = p.black },
    SpecialKey               = { fg = p.grey3, bg = p.black },
    SpellBad                 = { fg = p.red2, bg = p.black },
    SpellCap                 = { fg = p.red2, bg = p.black },
    SpellLocal               = { fg = p.orange2, bg = p.black },
    SpellRare                = { fg = p.orange2, bg = p.black },
    StatusLine               = { fg = p.none, bg = p.black },
    StatusLineNC             = { link = 'StatusLine' },
    Substitute               = { link = 'CurSearch' },
    TabLine                  = { fg = p.black, bg = p.black },
    TabLineFill              = { fg = p.black, bg = p.black },
    TabLineSel               = { fg = p.black, bg = p.black },
    TermCursor               = { fg = p.none, bg = p.blue4c1 },
    TermCursorNC             = { fg = p.none, bg = p.blue4c1 },
    TermNormal               = { fg = p.text, bg = p.black },
    Title                    = { fg = p.text, bg = p.black },
    Visual                   = { fg = p.none, bg = p.blue4 },
    VisualNOS                = { fg = p.none, bg = p.blue4 },
    WarningMsg               = { fg = p.orange2, bg = p.none },
    Whitespace               = { fg = p.grey4, bg = p.none, sp = p.grey4 },
    WildMenu                 = { fg = p.blue1, bg = p.blue4c1 },
    WinBar                   = { fg = p.text, bg = p.black },
    WinBarNC                 = { fg = p.text, bg = p.black },
    WinSeparator             = { fg = p.grey4, bg = p.none },
    lCursor                  = { fg = p.black, bg = p.blue1 },
    DiffAdd                  = { fg = p.green2, bg = p.green2 },
    DiffChange               = { fg = p.orange2, bg = p.orange1 },
    DiffDelete               = { fg = p.red2, bg = p.red1 },
    DiffText                 = { fg = p.text, bg = p.black },
    healthError              = { fg = p.red2, bg = p.red1 },
    healthSuccess            = { fg = p.green2, bg = p.green2 },
    healthWarning            = { fg = p.orange2, bg = p.orange1 },
    Menu                     = { fg = p.blue1, bg = p.black },
    Scrollbar                = { link = 'PmenuSbar' },
    Tooltip                  = { fg = p.sea4, bg = p.black },
    Yank                     = { fg = p.orange2, bg = p.sea4 },
    WindowPickerWinBar       = { fg = p.text, bg = p.none },
    WindowPickerWinBarNC     = { fg = p.text, bg = p.none },
    WindowPickerStatusLine   = { fg = p.text, bg = p.none },
    WindowPickerStatusLineNC = { fg = p.text, bg = p.none },
}

M.syntax = {
    Boolean        = { fg = p.purple2, bg = p.none },
    Character      = { fg = p.blue5, bg = p.none },
    Comment        = { fg = p.grey3, bg = p.none },
    Conditional    = { fg = p.blue5, bg = p.none },
    Constant       = { fg = p.sea4, bg = p.none },
    Debug          = { fg = p.grey0, bg = p.none },
    Define         = { fg = p.blue1, bg = p.none },
    Delimiter      = { fg = p.text, bg = p.none },
    Error          = { fg = p.red2, bg = p.none },
    Exception      = { fg = p.sea4, bg = p.none },
    Float          = { fg = p.purple2, bg = p.none },
    Function       = { fg = p.blue1, bg = p.none },
    Method         = { fg = p.sea4, bg = p.none },
    Identifier     = { fg = p.text, bg = p.none },
    Ignore         = { fg = p.none, bg = p.none },
    Include        = { fg = p.blue1, bg = p.none },
    Keyword        = { fg = p.blue5, bg = p.none },
    Label          = { fg = p.blue5, bg = p.none },
    Macro          = { fg = p.none, bg = p.none },
    Number         = { fg = p.purple2, bg = p.none },
    Operator       = { fg = p.orange2, bg = p.none },
    PreCondit      = { fg = p.blue1, bg = p.none },
    PreProc        = { fg = p.blue1, bg = p.none },
    Repeat         = { fg = p.blue1, bg = p.none },
    Special        = { fg = p.blue1, bg = p.none },
    SpecialChar    = { fg = p.orange2, bg = p.none },
    SpecialComment = { fg = p.sea4, bg = p.none },
    Statement      = { fg = p.blue1, bg = p.none },
    StorageClass   = { fg = p.blue5, bg = p.none },
    String         = { fg = p.orange3, bg = p.none },
    Structure      = { fg = p.blue7, bg = p.none },
    Tag            = { fg = p.red2, bg = p.none },
    Todo           = { fg = p.salmon6, bg = p.none },
    Type           = { fg = p.blue1, bg = p.none },
    Typedef        = { fg = p.blue1, bg = p.none },
    Underlined     = { fg = p.green2, bg = p.none, underline = true, sp = p.green2 },
}

return M
